### ISSUE TITLE
Release v0.1!

### ISSUE THREAD

**Issue by aome510** [aome510/hackernews-TUI#10]
TODO list upon the release of the version `v0.1`:
- [x] research theme for better user experience.
- [x] add `README.md` for the application specification.
- [x] release on `crates.io`
- [ ] release on archlinux `aur`

**Comment by BachoSeven** [comment]
Hei, I was trying to package this for the AUR, the only issue is that there is no `Cargo.lock` so cargo will complain about `--locked`, which is [required](https://wiki.archlinux.org/index.php/Rust_package_guidelines#Building) by the archlinux packaging guidelines for reproducible builds. Could you fix this?

P.S. [Here](https://github.com/BachoSeven/aur/blob/master/hackernews_tui/PKGBUILD) is the PKGBUILD I've written for now.

**Comment by aome510** [comment]
Hi @BachoSeven, thanks for writing the PKGBUILD for this project. I'm not really familiar with the AUR publishing progress so really appreciate it :muscle: !
Regarding the `cargo.lock` I have included new changes in [v0.1.1](https://github.com/aome510/hackernews-TUI/releases/tag/v0.1.1). Feel free to ping me here if I miss something or you have any other questions.

**Comment by BachoSeven** [comment]
@aome510 Thanks for the quick response, I've now published version `0.1.1` the package to the [AUR](https://aur.archlinux.org/packages/hackernews_tui/)!

**Comment by aome510** [comment]
Thanks, @BachoSeven. Installed using `yay` and it works on my machine! I have also updated the `README.md`
