### ISSUE TITLE
"Failed to get stories" on FreeBSD

### ISSUE THREAD

**Issue by phips** [aome510/hackernews-TUI#100]
Hello,

Would you have any idea why the client fails to get stories on an ec2 FreeBSD machine, yet a `curl` works just fine please?

Installed via `cargo install hackernews_tui --locked`

Thanks!

<img width="857" alt="Screenshot 2023-12-21 at 14 11 03" src="https://github.com/aome510/hackernews-TUI/assets/329022/7d5f94a6-0722-407e-960d-4b7285494c84">
<img width="857" alt="Screenshot 2023-12-21 at 14 11 29" src="https://github.com/aome510/hackernews-TUI/assets/329022/9eec3143-fd7c-48cb-9ad7-b147fdcc64f2">

**Comment by aome510** [comment]
Is this a consistent error which happens every time you start the application? Can you also share the application log in `.cache` folder?

**Comment by phips** [comment]
Hello @aome510 — yes, everytime. Log should be attached, thanks!

[hn-tui.log](https://github.com/aome510/hackernews-TUI/files/13751574/hn-tui.log)

**Comment by aome510** [comment]
Maybe related to https://github.com/algesten/ureq/issues/637. I suspect this issue may involve the network setting of your machine. Can you checkout https://github.com/aome510/hackernews-TUI/tree/100-debug and run `cargo run` to see if there is a panic? The difference between that branch and latest `main` is

```diff
 fn main() {
+    let d = ureq::head("https://google.com").call().unwrap();
+    println!("{d:?}");
+
```

**Comment by phips** [comment]
<img width="938" alt="Screenshot 2023-12-24 at 15 23 03" src="https://github.com/aome510/hackernews-TUI/assets/329022/167718ba-4343-4159-812a-f59926643239">

A ha! That might be it, yes. There is ipv6 on this machine too. Hmm. Frustrating that the module doesn't work with the transport the world is trying to move towards, isn't it? 🤔 

I'll try disabling it and see if it plays ball. But ultimately that's not the correct answer. Of course, I appreciate that is not this project's doing - ureq needs to get with the status quo 😄

**Comment by aome510** [comment]
Thanks for confirmation. I can switch to https://docs.rs/reqwest/latest/reqwest/ if `ureq` has that limitation

**Comment by phips** [comment]
Is reqwest a bigger library than ureq? I don't suppose it ultimately matters. Shame ureq has such a fundamental thing as ipv6 missing really, isn't it.

**Comment by aome510** [comment]
> Is reqwest a bigger library than ureq? I don't suppose it ultimately matters. Shame ureq has such a fundamental thing as ipv6 missing really, isn't it.

yeah, bigger and more dependencies. It's more popular and has more features as well. The main reason I chose `ureq` in  the first place is that it's relatively minimal. Maybe, that's why it doesn't have a good support for ipv6.

**Comment by ryanmcgrath** [comment]
This may be resolved now since they [deployed IPV6 support](https://news.ycombinator.com/item?id=39099065).

(The issue is primarily that `ureq` does not implement a happy-eyeballs type feature - i.e, it won't try both ipv4 and ipv6 at the same time and choose whichever one works.)

**Comment by aome510** [comment]
> This may be resolved now since they [deployed IPV6 support](https://news.ycombinator.com/item?id=39099065).
> 
> (The issue is primarily that `ureq` does not implement a happy-eyeballs type feature - i.e, it won't try both ipv4 and ipv6 at the same time and choose whichever one works.)

@phips can you try again with the new change? I haven't had a chance to switch to `rewquest` yet. If it works, maybe the switch is not needed.

**Comment by phips** [comment]
Sadly nope @aome510 — still the same 😢 

![Screenshot 2024-01-28 at 12 50 48](https://github.com/aome510/hackernews-TUI/assets/329022/9f617254-162c-4664-be53-178a7e409bed)

**Comment by phips** [comment]
Just tested this with latest release, and it's working! 👏 Closing ticket…
