### ISSUE TITLE
`v0.8.0` crashes on startup, fails to create log file

### ISSUE THREAD

**Issue by herbygillot** [aome510/hackernews-TUI#52]
```
thread 'main' panicked at 'failed to create application's log file: No such file or directory (os error 2)', hackernews_tui/src/main.rs:132:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
```

It's crashing because the `$HOME/.cache` directory does not exist, which is where it wants to create the log file.

After doing:
```bash
$ mkdir ~/.cache
```

...`v0.8.0` starts up without issues.

**Comment by aome510** [comment]
hi @herbygillot. Thanks for reporting. 

This should be fixed in https://github.com/aome510/hackernews-TUI/commit/be6b431b975839e15bf703beee2bab7348095bac. Will release a new version (`0.8.1`) shortly with the fix.

**Comment by herbygillot** [comment]
OK, fix confirmed.  BTW, `hackernews-tui` is available via MacPorts: https://ports.macports.org/port/hackernews-tui/

That's an option for those who want to install it on macOS.

**Comment by aome510** [comment]
@herbygillot thanks for confirming and mentioning MacPorts. Added a new method to `README`!
