### ISSUE TITLE
Question/feature: how to adjust the number of articles shown on main page?

### ISSUE THREAD

**Issue by reportaman** [aome510/hackernews-TUI#64]
Currently on my computer hackernews_tui shows just 19 articles on "front page". How can I make it show more articles?

**Comment by aome510** [comment]
Hi, I guess it shows 19 articles for the **first** page. You can press `n` (default binding for `next_page` command) to go the  second page.

**Comment by aome510** [comment]
If you want to adjust the number of items each page show, I'm afraid `hackernews_tui` doesn't support that feature atm.
