### ISSUE TITLE
Request: support XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by qubidt** [aome510/hackernews-TUI#65]
Feature request: support the [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) specification by checking `$XDG_CONFIG_HOME/hackernews_tui/hn-tui.toml` first, and then falling back to the `~/.config` if it doesn't exist.

**Comment by aome510** [comment]
Hi @qubidt. Sorry for the delay. I made the change in https://github.com/aome510/hackernews-TUI/commit/f99380ed30a9f0897be67ba8a6f2e1145f4f6717.

A new file finding logic is indicated in [here](https://github.com/aome510/hackernews-TUI/commit/f99380ed30a9f0897be67ba8a6f2e1145f4f6717). 

In short, `hackernews-tui` will look into `$XDG_CONFIG_HOME/hn-tui.toml` then fall back to `$HOME/.config/hn-tui.toml`.

**Comment by qubidt** [comment]
:raised_hands: awesome! seems to work correctly, thank you
