### ISSUE TITLE
Default to opening story in browser if there is no article

### ISSUE THREAD

**Issue by huyz** [aome510/hackernews-TUI#69]
I'm used to hitting a particular keyboard shortcut to open in my browser the article associated with a story.  But some stories, e.g. "Ask HN" don't have an associated article.  In that case, I would prefer for the story page to be open in the browser.  That way, I don't have to switch mental model (and keyboard shortcut) whenever I get to an "internal" story.

In other words, "Open in browser the article associated with the focused story" should default to "Open in browser the focused story" if there is no article associated with the story

**Comment by aome510** [comment]
Hi @huyz. Sorry for the delay, with the [new version `0.10.1`](https://github.com/aome510/hackernews-TUI/releases/tag/v0.10.1) released, this behaviour should be implemented with "open article in browser" command. 

Please note that there are some changes in the list of default shortcuts in the new version, which may break your current config file.

**Comment by huyz** [comment]
Thanks @aome510
