### ISSUE TITLE
Failed to execute the command: 'article_md --format html'

### ISSUE THREAD

**Issue by ivancernja** [aome510/hackernews-TUI#73]
I am unable to open the article view inside the terminal. 

The description tells me to configure the 'article_parse_command' option as described on the link:
https://github.com/aome510/hackernews-TUI/blob/main/config.md#article-parse-command

But that blob doesn't exist.

What am I doing wrong?

**Comment by aome510** [comment]
Hi, recently I moved the config doc to another folder. You can use this link instead https://github.com/aome510/hackernews-TUI/blob/main/doc/config.md#article-parse-command

**Comment by ivancernja** [comment]
That helped, thanks so much!
