### ISSUE TITLE
Why the results aren't the same as in the web?

### ISSUE THREAD

**Issue by ftpd** [aome510/hackernews-TUI#79]
![03013cf918d23c53b2c6ad0240a366111f7d66e4](https://user-images.githubusercontent.com/1644381/186717079-29f95097-e3c4-4f70-b69c-3fcd6f53c102.png)

I've decided to give hackernews-TUI a chance today but right after running it I've seen it shows different stories than they are on the web. Why? Do I use it somehow wrong?

**Comment by aome510** [comment]
For tabs other than **front page**, it can either show the stories sorted by date or by points because [HN Algolia API](https://hn.algolia.com/api) is used for that. **front page** stories are fetched using [HN official API](https://github.com/HackerNews/API).

This can be resolved by using a mix of both APIs.

**Comment by aome510** [comment]
Hi @ftpd. I've updated the app in #80 to show `shown_hn` and `ask_hn` stories in the same order as in the web. Can you try to the latest build to confirm that it works?

**Comment by ftpd** [comment]
Sorry, I was on holidays.

I still see some differences.

**Comment by aome510** [comment]
> Sorry, I was on holidays.

No worries. 

> I still see some differences.

Do u have any pictures of such differences? Mine is similar

**Comment by ftpd** [comment]
This is how it looks for me:
![ask](https://user-images.githubusercontent.com/1644381/190927779-1b2d9fb1-77af-4a5d-9b99-130cacb2bd43.jpg)

And frontpage looks fine:
![main](https://user-images.githubusercontent.com/1644381/190927792-ba9249e3-307f-4b92-8786-39da8fed50a6.jpg)

**Comment by aome510** [comment]
Looks like you're using the old build of `hackernews_tui` (as the `ask-hn` stories are still sorted by date). Can u try it with the latest build from `main`:

```shell
git clone https://github.com/aome510/hackernews-TUI.git && cd hackernews-TUI
cargo run
```

**Comment by ftpd** [comment]
Oh, I've just assumed there is a new release ;-) I will build it, but no sooner than today's evening (CEST). I will let you know, sorry for the inconvenience.

**Comment by ftpd** [comment]
Aaaaaaaand I forgot.

Now I've build from today's master - it works fine. Thanks, I will wait for the new release.

**Comment by aome510** [comment]
> Aaaaaaaand I forgot.
> 
> Now I've build from today's master - it works fine. Thanks, I will wait for the new release.

Great. Thanks for the confirmation. I'll release a new version soon
