### ISSUE TITLE
Feature request: open the app at a specific comment view

### ISSUE THREAD

**Issue by AdrianVollmer** [aome510/hackernews-TUI#86]
This app looks amazing. I'm often reading HN with an RSS client and I'm thinking of a way to open the comments with `hackernews_tui`. Have you considered introducing an optional  positional argument that takes a URL and opens the appropriate view directly?

**Comment by aome510** [comment]
Hi @AdrianVollmer, I have not, but implementing one shouldn't be too difficult.
