### ISSUE TITLE
'open' command on Linux

### ISSUE THREAD

**Issue by qubidt** [aome510/hackernews-TUI#87]
Currently, the `url_open_command` has a hard-coded default of `open`:

https://github.com/aome510/hackernews-TUI/blob/3da2bc07034b451dedfea434f00946fa0025e197/hackernews_tui/src/config/mod.rs#L51-L54

That is (AFAIK) a MacOS-ism. On most Linux systems, the equivalent command is [`xdg-open`](https://linux.die.net/man/1/xdg-open). Since we're compiling separate binaries for each anyways, could the default be set to `xdg-open` when targeting Linux? This would provide a much more sane default for Linux users.

**Comment by aome510** [comment]
Updated in #88. Can you try the new changes in the PR to see if they work?
