### ISSUE TITLE
Error:failed to execute command

### ISSUE THREAD

**Issue by kirk781** [aome510/hackernews-TUI#89]
When opening in article view, it gives the error, failed to execute command:

article_md --format html [url of the article].
Please make sure you have configured the "article_parse_command" option as described in the following link.

The link leads to nowhere. I also can't open articles in the web browsers. Do I need to configure a command line based web browser like Lynx to do that?

I am on the latest version of the app installed via Cargo. The OS is Manjaro [it is capable of installing via Arch repos but cargo gets even earlier updates for Rust applications, hence I chose it over the AUR].

**Comment by aome510** [comment]
> The link leads to nowhere. I also can't open articles in the web browsers. Do I need to configure a command line based web browser like Lynx to do that?

Sorry for the confusion. Recently, I updated the folder name in the repo, so the old link doesn't work now. The new link should be https://github.com/aome510/hackernews-TUI/blob/main/docs/config.md#article-parse-command

I assume you're a Linux user. The default URL open command is `open` which doesn't work in Linux (context: https://github.com/aome510/hackernews-TUI/issues/87). You can configure it by updating the `~/.config/hn-tui.toml`. Example config file for your reference: https://github.com/aome510/hackernews-TUI/blob/main/examples/hn-tui.toml#L10
