### ISSUE TITLE
Could not compile `hackernews_tui` due to errors 

### ISSUE THREAD

**Issue by zakwanhisham** [aome510/hackernews-TUI#97]
Hi,I tried to installed `hackernews_tui` using cargo but it gave out compilation error. 

Here are the my prompt:
```sh
cargo install hackernews_tui
```
Here are some of the error:
```sh
expected `toml::value::Value`, found `toml::Value`
```
On my machine, I use rust nightly. I attached here the image of some of the error. Thank you.

![image](https://github.com/aome510/hackernews-TUI/assets/94990170/f5bd7e20-013e-4df2-9d22-10c2fa03d76f)

**Comment by aome510** [comment]
I think it's because of recent dependency upgrade. Can you try

```
cargo install hackernews_tui --locked
```

**Comment by zakwanhisham** [comment]
Hi, thank you for the reply. I have installed using the method you suggest and I also make a pr on the README.md changes. I mark this issue as solve. Once again, thank you
